/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isucv.restaurant.view;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Equipo Ingenieria de Software <David Contreras, Fabian Ramos, Ruben Maza>
 */
public class Dbg___WndSideSelectorDebugger extends javax.swing.JFrame {

    /**
     * Creates new form Dbg___WndSideSelectorDebugger
     */
    public Dbg___WndSideSelectorDebugger() {
        initComponents();
        
        // Adjust Table's Column width
        tableResults.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableResults.getColumnModel().getColumn(1).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdOpenSubWindow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaximumSides = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Depurador del Selector de Contornos");
        setResizable(false);

        cmdOpenSubWindow.setText("Seleccionar Contornos");
        cmdOpenSubWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOpenSubWindowActionPerformed(evt);
            }
        });

        jLabel1.setText("Contornos Maximos");

        txtMaximumSides.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtMaximumSides.setText("3");

        tableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdOpenSubWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaximumSides, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdOpenSubWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaximumSides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOpenSubWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOpenSubWindowActionPerformed
        // ABRIR LA VENTANA DE SELECCION DE CONTORNOS Y RECUPERAR LOS RESULTADOS
        
        int maxSides = Integer.getInteger(txtMaximumSides.getText());
        ISelectorContornos wnd = new ISelectorContornos();
        // FALTA ESTABLECER LA CANTIDAD MAXIMA DE CONTORNOS POSIBLES
        // DENTRO DE LA INSTANCIA DE LA CLASE SelectorContornos A TRAVES
        // DE UN ATRIBUTO DE DICHA CLASE
        // AYUDA:
        //    wnd.setMaximumSides(maxSides);
        wnd.setVisible(true);
        
        // Limpiar la tabla
        // FALTA COLOCAR EL CODIGO PARA ELIMINAR TODAS LAS FILAS (si existen)
        
        // ADEVERTENCIA!: Este codigo puede causar un bloqueo de JAVA
        // en el caso donde la ventana de selector de contornos se ejecute en el
        // mismo Thread que esta ventana/codigo.
        // Si la aplicacion se bloquea al hacer click en este boton. Entonces
        // la razon es ESTE bloque while() con el Thread.sleep() en su interior
        while (wnd.isVisible())
        {
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(Dbg___WndSideSelectorDebugger.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // OBTENER LOS RESULTADOS AQUI!
        // AYUDA: 
        //
        // ArrayList<ContadorContorno> MiLista_ContadorContorno;
        // MiLista_ContadorContorno = wnd.getSeleccion(); <--- Falta Implementar
        // for (i = 0; i < MiLista_ContadorContorno.Length; i++)   <---- No estoy seguro
        // {
        //    tableResults.addrow(MiLista...[i].Cantidad, MiLista...[i].Descr);
        // }
        
        // Eliminar el selector de contornos
        wnd.dispose();
    }//GEN-LAST:event_cmdOpenSubWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dbg___WndSideSelectorDebugger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dbg___WndSideSelectorDebugger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dbg___WndSideSelectorDebugger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dbg___WndSideSelectorDebugger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dbg___WndSideSelectorDebugger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdOpenSubWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableResults;
    private javax.swing.JFormattedTextField txtMaximumSides;
    // End of variables declaration//GEN-END:variables
}
