/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isucv.restaurant.view;

import isucv.restaurant.controller.Controller;
import static isucv.restaurant.controller.Controller.FindOrder;
import static isucv.restaurant.controller.Controller.GetPendingOrders;
import isucv.restaurant.model.ContadorContorno;
import isucv.restaurant.model.ContadorEspecialidad;
import isucv.restaurant.model.Pedido;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Equipo Ingenieria de Software <David Contreras, Fabian Ramos, Ruben Maza>
 */
public class WndCocinaPedidos extends javax.swing.JFrame {

    private final static int ORDERS_COLUMN_ID = 0;
    private final static int ORDERS_COLUMN_DISHES = 1;
    private final static int ORDERS_COLUMN_SIDES = 2;
    private final static int ORDERS_COLUMN_TIME = 3;
    
    private final static int ORDER_COLUMN_QUANTITY = 0;
    private final static int ORDER_COLUMN_DESCRIPTION = 1;
    
    /**
     * Creates new form WndCocinaPedidos
     */
    public WndCocinaPedidos() {
        initComponents();
        
        // Center Column text for both JTables
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_ID).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_DISHES).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_SIDES).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_TIME).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(ORDER_COLUMN_QUANTITY).setCellRenderer(centerRenderer);
        
        // Setup Column Width for both JTables
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_ID).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_ID).setMaxWidth(120);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_DISHES).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_SIDES).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(ORDERS_COLUMN_TIME).setPreferredWidth(80);
        
        jTable2.getColumnModel().getColumn(ORDER_COLUMN_QUANTITY).setPreferredWidth(40);
        jTable2.getColumnModel().getColumn(ORDER_COLUMN_QUANTITY).setMaxWidth(80);
        jTable2.getColumnModel().getColumn(ORDER_COLUMN_DESCRIPTION).setPreferredWidth(360);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblIdPedido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preparación de Pedidos");
        setMinimumSize(new java.awt.Dimension(572, 469));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(2454),  new Integer(1),  new Integer(0),  new Float(15.0)},
                { new Integer(2455),  new Integer(1),  new Integer(1),  new Float(17.0)},
                { new Integer(2456),  new Integer(8),  new Integer(3),  new Float(35.0)},
                { new Integer(2471),  new Integer(1),  new Integer(1),  new Float(7.0)},
                { new Integer(2472),  new Integer(2),  new Integer(4),  new Float(38.0)},
                { new Integer(2473),  new Integer(2),  new Integer(0),  new Float(30.0)},
                { new Integer(2474),  new Integer(0),  new Integer(4),  new Float(8.0)}
            },
            new String [] {
                "Id Pedido", "Total de Platos", "Total de Contornos", "Tiempo Total (minutos)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("Cola de Pedidos por Preparar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pedido");
        jLabel3.setToolTipText("");

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Pollo a la Canasta"},
                {null, "Arroz Blanco"},
                {null, "Yuca Frita"},
                { new Integer(2), "Pizza Margarita"},
                { new Integer(1), "Hamburguesa de carne"},
                {null, "Papas Fritas"},
                { new Integer(3), "Papas Fritas"},
                { new Integer(1), "Nestea Durazno"}
            },
            new String [] {
                "Cantidad", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jButton1.setText("Despachar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblIdPedido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblIdPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdPedido.setText("2456");
        lblIdPedido.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pedido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("8 Platos");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("3 Contornos");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(lblIdPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(2, 2, 2))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void UpdateTable(int id)
    {
        // Actualiza la tabla con la informacion de Especialidades y Contornos seleccionados
        DefaultTableModel md = (DefaultTableModel) jTable2.getModel();
        md.setRowCount(0); // Eliminar el contenido actual de la tabla
        
        //Contadores que se mostraran
        int contSpecialities=0,contSides=0;
        
        //conseguir el pedido con ID
        Pedido ped;
        ped=FindOrder(id);
        // Mostrar Especialidades
        for (int i = 0; i < ped.GetSpecialities().size(); i++)
        {
            // Agregar especialidad
            ContadorEspecialidad e = ped.GetSpecialities().get(i);
            //Mostramos solo las especialidades que tienen un count mayor a 0 (que han sido pedidos)
            //En finalizar orden removemos estos mismos que tienen count igual a 0 para tener el array solo con ordenes pedidas
            if(e.GetCount()>0)
            {
                md.addRow(new Object[] {e.GetCount(), e.GetSpeciality().GetName()});
                contSpecialities+=e.GetCount();

                // Agregar contornos incluidos
                if (e.GetSides() == null || e.GetSides().size()==0)
                    continue;

                for (int sub = 0; sub < ped.GetSpecialities().get(i).GetSides().size(); sub++)
                {
                    ContadorContorno c = e.GetSides().get(sub);
                    md.addRow(new Object[] {c.GetCount(), "          " + c.GetSide().GetName(), null, null});
                }
            }
        }
        // Mostrar Contornos Adicionales
        for (int a = 0; a < ped.GetSides().size(); a++)
        {
            // Agregar Contorno
            ContadorContorno aux = ped.GetSides().get(a);
            md.addRow(new Object[] {aux.GetCount(), aux.GetSide().GetName()});
            contSides+=aux.GetCount();
        } 
        jLabel5.setText(String.format(Integer.toString(contSpecialities) + " Platos "));
        jLabel6.setText(String.format(Integer.toString(contSides) + " Contornos ")); 
    }
    
    public void UpdateTablePedidos(){
        //Boton despachar pedido deshabilitado hasta q se seleccione un pedido
        jButton1.setEnabled(false);
        DefaultTableModel md1 = (DefaultTableModel) jTable1.getModel();
            md1.setRowCount(0); // Eliminar la tabla
            
            DefaultTableModel md2 = (DefaultTableModel) jTable2.getModel();
            md2.setRowCount(0); // Eliminar la tabla
        //Condicion, si no existen pedidos, no mostramos nada
        if(GetPendingOrders().isEmpty()==false)
        {
            int tim=0;
            int id;
            int CantContorno;
            int CantEspecialidad;
            //Borramos todo para cargar
                lblIdPedido.setText(" ");
                jLabel5.setText("0 Platos");
                jLabel6.setText("0 Contornos");

                //Cargamos desde pendingorders
                for(int i=0;i < GetPendingOrders().size();i++)
                {
                    //ID
                    id=GetPendingOrders().get(i).GetId();
                    //Cantidad platos
                    CantEspecialidad=GetPendingOrders().get(i).GetSpecialities().size();
                    //cantidad platos
                    CantContorno=GetPendingOrders().get(i).GetSides().size();

                    //Calculo total time
                    //Suma de tiempos, si size nos devuelve q tiene elementos
                    for(int j=0;j < GetPendingOrders().get(i).GetSpecialities().size();j++)
                    {
                            tim+=GetPendingOrders().get(i).GetSpecialities().get(j).GetSpeciality().GetTime();
                    }

                    //Suma de tiempos, cantidad de contornos adiciones
                    //Multiplicamos por 2, ya que cada contorno adicional dura 2 min cocinandose
                    tim+=(2)*GetPendingOrders().get(i).GetSides().size();

                    //Codigo llenado de table
                      md1.addRow(new Object[] {id,CantEspecialidad,CantContorno,tim});   
                }
        }else{
                lblIdPedido.setText("No");
                jLabel5.setText("Existen");
                jLabel6.setText("Pedidos");
        }
    }
    // Permite retornar a la ventana de seleccion de tarea al cerrar
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        UpdateTablePedidos();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int idped=0;
        if(lblIdPedido.getText()=="No")
        {
            //cerramos ventana
            this.setVisible(false);
        }
        else
        {
                //Movemos la orden elegida a la cola de despacho de mesonero
                DefaultTableModel md = (DefaultTableModel) jTable1.getModel();
            if (md.getRowCount() < 1)
                return;

            for (int i = md.getRowCount() - 1; i >= 0; i--)
            {
                if (jTable1.isRowSelected(i))
                {
                    //Encontramos la fila para obtener el num de pedido
                    idped=Integer.parseInt(jTable1.getValueAt(i,0).toString());
                }
            }
        }
        Pedido p;
        p=FindOrder(idped);
        
        //Movemos el pedido al mesonero ordersready y borramos el pedido de pendingorders
        Controller.GetOrdersReady().add(p);
        for(int y=0;y<Controller.GetPendingOrders().size();y++)
        {
            if(Controller.GetPendingOrders().get(y).GetId()==idped)
            {
                    Controller.GetPendingOrders().remove(y);
            }
        }
        //Borramos la 2da table
        DefaultTableModel md2 = (DefaultTableModel) jTable2.getModel();
        md2.setRowCount(0);
        //Se actualiza nuevamente la table de pedidos
        UpdateTablePedidos();
        //Se deshabilita boton de despacho hasta q se seleccione otra opcion
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int id=0;
        DefaultTableModel md = (DefaultTableModel) jTable1.getModel();
        if (md.getRowCount() < 1)
            return;
        
        for (int i = md.getRowCount() - 1; i >= 0; i--)
        {
            if (jTable1.isRowSelected(i))
            {
                //Habilitar boton Despachar pedido
                jButton1.setEnabled(true);
                id=Integer.parseInt(jTable1.getValueAt(i,0).toString());
                lblIdPedido.setText(Integer.toString(id));     
            }
        }
        UpdateTable(id);
    }//GEN-LAST:event_jTable1MouseClicked

    // Almacena la ventana principal que muestra esta ventana
    private JFrame ParentWindow = null;
    
    // Permite intercambiar las ventanas activas del controlador al mostrarse
    // y ocultarse
    @Override
    public void setVisible(boolean value)
    {        
        super.setVisible(value);
        
        if (!value)
        {
            Controller.OpenSubTask(1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblIdPedido;
    // End of variables declaration//GEN-END:variables
}
