/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isucv.restaurant.view;

import isucv.restaurant.controller.Controller;
import isucv.restaurant.model.Contorno;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Equipo Ingenieria de Software <David Contreras, Fabian Ramos, Ruben Maza>
 */
public class WndEditorContornos extends javax.swing.JFrame {

    private final static int COLUMN_DESCRIPTION = 0;
    private final static int COLUMN_PRICE = 1;
    private final static int COLUMN_AVAILABLE = 2;
    
    /**
     * Creates new form wndPrincipal
     */
    public WndEditorContornos() {
        initComponents();
        
        // Establecer ancho de columnas para la Tabla
        Table.getColumnModel().getColumn(COLUMN_DESCRIPTION).setPreferredWidth(160);
        Table.getColumnModel().getColumn(COLUMN_PRICE).setPreferredWidth(60);
        Table.getColumnModel().getColumn(COLUMN_AVAILABLE).setPreferredWidth(60);
        
        // Rellenar el Table con el contenido actual de la cartelera (Contornos)
        DefaultTableModel md = (DefaultTableModel) Table.getModel();
        md.setRowCount(0); // Eliminar el contenido del Table
        
        if (Controller.GetBillboardSides().size() > 0)
        {
            int i;
            for (i = 0; i < Controller.GetBillboardSides().size(); i++)
            {
                // Celdas:
                // Nombre, Precio, Visible
                Contorno e = Controller.GetBillboardSides().get(i);
                
                md.addRow(new Object[] {e.GetName(), e.GetPrice(), e.GetVisible()});
            }
        }
        
        // Actualizar Labels Estadisticos
        lblTotal.setText(Table.getRowCount() + " Contornos totales.");
        
        int i;
        int count = 0;
        for (i = 0; i < Table.getRowCount(); i++)
        {
            Object val = Table.getModel().getValueAt(i, COLUMN_AVAILABLE);
            if (val != null && (boolean)val)
                count++;
        }
        lblVisible.setText(count + " Contornos Visibles en Cartelera.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        cmdApplyChanges = new javax.swing.JButton();
        cmdDiscardChanges = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdAdd = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblVisible = new javax.swing.JLabel();
        cmdDeleteAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Contornos");
        setMinimumSize(new java.awt.Dimension(580, 393));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Papas Fritas",  new Float(210.7),  new Boolean(false)},
                {"Papas al Vapor",  new Float(180.4),  new Boolean(true)},
                {"Yuca Frita",  new Float(110.5),  new Boolean(true)},
                {"Arroz Blanco",  new Float(70.0),  new Boolean(true)},
                {"Arroz Frito",  new Float(70.0),  new Boolean(false)},
                {"Ensalada Rallada",  new Float(110.0),  new Boolean(true)},
                {"Tajadas",  new Float(90.0),  new Boolean(true)},
                {"Nestea Durazno",  new Float(90.0),  new Boolean(true)}
            },
            new String [] {
                "Descripción", "Precio", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        cmdApplyChanges.setText("Aplicar Cambios");
        cmdApplyChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdApplyChangesActionPerformed(evt);
            }
        });

        cmdDiscardChanges.setText("Descartar");
        cmdDiscardChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDiscardChangesActionPerformed(evt);
            }
        });

        jLabel1.setText("Contornos Almacenados Actualmente");

        cmdAdd.setText("Agregar");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdDelete.setText("Eliminar");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        lblTotal.setText("# Contornos Totales");

        lblVisible.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVisible.setText("# Contornos Disponibles en Cartelera");

        cmdDeleteAll.setText("Eliminar Todo");
        cmdDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal)
                                    .addComponent(lblVisible))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(cmdApplyChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdDiscardChanges, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmdApplyChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdDiscardChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVisible))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDeleteAll)
                        .addGap(0, 262, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Permite retornar a la ventana de seleccion de tarea al cerrar
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void cmdDiscardChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDiscardChangesActionPerformed
        // Cierra esta Ventana y descarta los cambios
        this.setVisible(false);
    }//GEN-LAST:event_cmdDiscardChangesActionPerformed

    private void cmdDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteAllActionPerformed
        // Elimina todos los elementos de la lista
        DefaultTableModel md = (DefaultTableModel) Table.getModel();
        md.setRowCount(0);
        
        UpdateInternalStatistics();
    }//GEN-LAST:event_cmdDeleteAllActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        // Agrega un elemento adicional (fila) a la tabla
        DefaultTableModel md = (DefaultTableModel) Table.getModel();
        md.setRowCount(md.getRowCount() + 1);
        
        UpdateInternalStatistics();
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        // Elimina uno o varios elementos (filas) seleccionados de la tabla      
        DefaultTableModel md = (DefaultTableModel) Table.getModel();
        if (md.getRowCount() < 1)
            return;
        
        int i;
        for (i = md.getRowCount() - 1; i >= 0; i--)
        {
            if (Table.isRowSelected(i))
                md.removeRow(i);
        }
        
        UpdateInternalStatistics();
    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void TablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablePropertyChange
         UpdateInternalStatistics();
    }//GEN-LAST:event_TablePropertyChange

    private void cmdApplyChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdApplyChangesActionPerformed
        // Elimina el contenido actual de la cartelera (Contornos)
        // y lo sustituye con el almacenado en esta ventana
        
        Controller.SetBillboardSides(new ArrayList<>());
        
        DefaultTableModel md = (DefaultTableModel) Table.getModel();
        if (md.getRowCount() > 0)
        {
            // Celdas:
            // Nombre, Precio, Visible
            
            int i;
            for (i = 0; i < md.getRowCount(); i++)
            {
                Contorno d = new Contorno((String)md.getValueAt(i, 0),
                    (Float)md.getValueAt(i, 1),
                    (Boolean)md.getValueAt(i, 2));
                
                if (d.GetVisible() == null)
                    d.SetVisible(false);
                
                if (d.GetPrice() == null)
                    d.SetPrice(0.0f);
                
                Controller.GetBillboardSides().add(d);
            }
        }
        
        // REFACTOR:change
        //Controller.GetBillboard().SetTotalSides(md.getRowCount());
        this.setVisible(false);
    }//GEN-LAST:event_cmdApplyChangesActionPerformed

    // Actualiza las estadisticas sobre contornos totales y visibles
    // mostradas en los Labels de la ventana
    private void UpdateInternalStatistics()
    {
        lblTotal.setText(Table.getRowCount() + " Contornos totales.");
        int i;
        int count = 0;
        for (i = 0; i < Table.getRowCount(); i++)
        {
            Object val = Table.getModel().getValueAt(i, COLUMN_AVAILABLE);
            if (val != null && (boolean)val)
                count++;
        }
        lblVisible.setText(count + " Contornos Visibles en Cartelera.");
    }
    
    // Almacena la ventana principal que muestra esta ventana
    private JFrame ParentWindow = null;
    
    // Permite intercambiar las ventanas activas del controlador al mostrarse
    // y ocultarse
    @Override
    public void setVisible(boolean value)
    {        
        super.setVisible(value);
        
        if (!value)
        {
            Controller.OpenSubTask(1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdApplyChanges;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdDeleteAll;
    private javax.swing.JButton cmdDiscardChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVisible;
    // End of variables declaration//GEN-END:variables
}
